/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocomoJava;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Sapphire
 */
public class EquationDefault extends javax.swing.JFrame {
    /**
     * Factors in equations for calculation
     */
    public static double A = 2.94;
    public static double B = 0.91;
    public static double C = 3.67;
    public static double D = 0.28;
    
    /**
     * Default factors used when reset
     */
    public static double defaultA = 2.94;
    public static double defaultB = 0.91;
    public static double defaultC = 3.67;
    public static double defaultD = 0.28;

    /**
     * Creates new form EquationDefault
     */
    public EquationDefault() {
        initComponents();
        this.setTitle("Equation Factors");
        this.getContentPane().setBackground(Color.white);
        this.setValues();
    }
    
    public void setValues(){
        valueA.setText(String.valueOf(A));
        valueB.setText(String.valueOf(B));
        valueC.setText(String.valueOf(C));
        valueD.setText(String.valueOf(D));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valueB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        valueA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        valueC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valueD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        setEqFactorbtn = new javax.swing.JButton();
        resetEqFactorbtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Exponet Equation");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText(" + 0.01 * (SF1+ ... + SF5)");

        jLabel3.setText("B = ");

        valueB.setBackground(new java.awt.Color(204, 204, 204));
        valueB.setText("0.91");
        valueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(valueB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Effort Equation");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("PM = EM1 * ... * EM17 * ");

        valueA.setBackground(new java.awt.Color(204, 204, 204));
        valueA.setText("2.94");
        valueA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueAActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("* (Size)^B + (ASLOC*(AT/100)/ATPROD)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(valueA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Schedule Equation");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("TDEV = [ ");

        valueC.setBackground(new java.awt.Color(204, 204, 204));
        valueC.setText("3.67");
        valueC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueCActionPerformed(evt);
            }
        });

        jLabel9.setText("* PM^(");

        valueD.setBackground(new java.awt.Color(204, 204, 204));
        valueD.setText("0.28");
        valueD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueDActionPerformed(evt);
            }
        });

        jLabel10.setText("+ 0.2*(B-0.91))] * (SCED% / 100)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valueD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valueC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(valueD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setEqFactorbtn.setBackground(new java.awt.Color(102, 255, 102));
        setEqFactorbtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        setEqFactorbtn.setText("OK");
        setEqFactorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setEqFactorbtnActionPerformed(evt);
            }
        });

        resetEqFactorbtn.setBackground(new java.awt.Color(102, 255, 102));
        resetEqFactorbtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        resetEqFactorbtn.setText("Reset");
        resetEqFactorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEqFactorbtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(102, 255, 102));
        cancelBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        
        lblEffortEquationFor = new JLabel("Effort Equation for Early design Model");
        
        JPanel panel = new JPanel();
        panel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
        panel.setBackground(Color.WHITE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(138)
        			.addComponent(setEqFactorbtn, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(370, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(216)
        			.addComponent(jLabel5)
        			.addContainerGap(244, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(232)
        			.addComponent(jLabel1)
        			.addContainerGap(234, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(240)
        			.addComponent(lblEffortEquationFor)
        			.addContainerGap(284, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(243)
        			.addComponent(resetEqFactorbtn, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        			.addGap(36)
        			.addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
        			.addGap(23))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(256)
        			.addComponent(jLabel4)
        			.addContainerGap(405, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(72)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addContainerGap())
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addContainerGap())
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGap(153)))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(2)
        			.addComponent(jLabel4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblEffortEquationFor)
        			.addGap(18)
        			.addComponent(panel, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel5)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(setEqFactorbtn)
        					.addComponent(resetEqFactorbtn))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(cancelBtn)
        					.addContainerGap())))
        );
        
        JLabel lblPmEm = new JLabel();
        lblPmEm.setText("PM = EM1 * ... * EM7 * ");
        panel.add(lblPmEm);
        
        textField = new JTextField();
        textField.setText("2.94");
        textField.setBackground(new Color(204, 204, 204));
        panel.add(textField);
        
        JLabel label_1 = new JLabel();
        label_1.setText("* (Size)^B + (ASLOC*(AT/100)/ATPROD)");
        label_1.setBackground(Color.WHITE);
        panel.add(label_1);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueBActionPerformed

    private void valueAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueAActionPerformed

    private void valueCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueCActionPerformed

    private void valueDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueDActionPerformed

    private void setEqFactorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setEqFactorbtnActionPerformed
        // TODO add your handling code here:
        String sA = valueA.getText().toString();
        String sB = valueB.getText().toString();
        String sC = valueC.getText().toString();
        String sD = valueD.getText().toString();
        double[] values = new double[4];
        try{
            values[0] = Double.valueOf(sA);
            values[1] = Double.valueOf(sB);
            values[2] = Double.valueOf(sC);
            values[3] = Double.valueOf(sD);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Illegal Inputs! Allows number between 0 and 10.");
            return;
        }
        for(int i=0; i<4; ++i){
            if(values[i]<0 || values[i]>10) {
                JOptionPane.showMessageDialog(null, "Please enter a number between 0 and 10.");
                return;
            }
        }
        A = values[0];
        B = values[1];
        C = values[2];
        D = values[3];
        this.dispose();
    }//GEN-LAST:event_setEqFactorbtnActionPerformed

    private void resetEqFactorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEqFactorbtnActionPerformed
        // TODO add your handling code here:
        A = defaultA;
        B = defaultB;
        C = defaultC;
        D = defaultD;
        this.setValues();
    }//GEN-LAST:event_resetEqFactorbtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.setValues();
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquationDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquationDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquationDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquationDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquationDefault().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton resetEqFactorbtn;
    private javax.swing.JButton setEqFactorbtn;
    private javax.swing.JTextField valueA;
    private javax.swing.JTextField valueB;
    private javax.swing.JTextField valueC;
    private javax.swing.JTextField valueD;
    private JLabel lblEffortEquationFor;
    private JTextField textField;
}
