
package cocomoJava;

import java.awt.Color;

/**
 *This class implements the schedule for developing the software
 * This cost driver applies to the entire project
 * It also contributes to the value of EAF
 * @author preethijprabhu
 * @version 1.0.0.0
 */
public class Sched extends javax.swing.JDialog {

    
    private double[] schedCoefficient = {1.50, 1.22, 1.00, 0.76, 0.63};
    
    /* 
     * Modification: 02/13/2017
     *  Add a new percentage array for the effort is not nomial when calculating the SCHED.
     */
    
    private double[] schedPercent = {0.75, 0.85, 1.00, 1.3, 1.6};
    
    CocomoDashboard cocoDash;

    public Sched(java.awt.Frame parent, boolean modal, String schedRating) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.cocoDash = (CocomoDashboard) parent;
        schedCombo.setSelectedItem(schedRating);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schedCombo = new javax.swing.JComboBox<>();
        schedLabel = new javax.swing.JLabel();
        schedOkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCHEDULE");

        schedCombo.setBackground(new java.awt.Color(204, 255, 255));
        schedCombo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VLOW", "LOW", "NOM", "HIGH", "VHIGH" }));

        schedLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedLabel.setText("Schedule:");

        schedOkBtn.setBackground(new java.awt.Color(102, 255, 102));
        schedOkBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedOkBtn.setText("OK");
        schedOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedOkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(schedLabel)
                        .addGap(18, 18, 18)
                        .addComponent(schedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(schedOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schedLabel))
                .addGap(18, 18, 18)
                .addComponent(schedOkBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schedOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedOkBtnActionPerformed
        this.cocoDash.setSchedule(String.valueOf(SCHEDefault.sched[schedCombo.getSelectedIndex()]),
                schedCombo.getSelectedItem().toString());
        this.cocoDash.getSchedEaf();
        this.setVisible(false);
    }//GEN-LAST:event_schedOkBtnActionPerformed

	public double getCoefficient(String schedRating) {
		double res = 1.00;
		switch(schedRating) {
			case "VLOW":
				res = schedCoefficient[0];
				break;
			case "LOW":
				res = schedCoefficient[1];
				break;
			case "NOM":
				res = schedCoefficient[2];
				break;
			case "HIGH":
				res = schedCoefficient[3]; 
				break;
			case "VHIGH":
				res = schedCoefficient[4];
				break;
			default:
				res = 1.00;
				break;
		}
		return res;
	}
        
        /*!
         * 1. Function Description:
         *     Returns the percent requested by different effort level.
         *     It can be used to get the percent given level string.
         *
         * 2. Parameters:
         *     schedRating: the string to deternmine the type of effort.
         *
         * 3. Creation Time and Owner: 02/13/2017; Zhibo Zhang
         */

        public double getPercent(String schedRating) {
		double res = 1.00;
		switch(schedRating) {
			case "VLOW":
				res = schedPercent[0];
				break;
			case "LOW":
				res = schedPercent[1];
				break;
			case "NOM":
				res = schedPercent[2];
				break;
			case "HIGH":
				res = schedPercent[3]; 
				break;
			case "VHIGH":
				res = schedPercent[4];
				break;
			default:
				res = 1.00;
				break;
		}
		return res;
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sched.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sched.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sched.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sched.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sched dialog = new Sched(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> schedCombo;
    private javax.swing.JLabel schedLabel;
    private javax.swing.JButton schedOkBtn;
    // End of variables declaration//GEN-END:variables
}
