/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocomoJava;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * Date 02/27/2017
 * @author Zhibo Zhang
 * 
 * Add a new schedule factor panel for individual setting.
 */

public class SCHEDefault extends javax.swing.JFrame {

    public static double[] sched = {1.43, 1.14, 1.00, 1.00, 1.00};
    private final double[] defSched = {1.43, 1.14, 1.00, 1.00, 1.00};
    
    /**
     * Creates new form SCHEDefault
     */
    public SCHEDefault() {
        
        initComponents();
        this.setTitle("Schedule Default Values");
        this.getContentPane().setBackground(Color.white);
        
        schedVL.setText(String.valueOf(sched[0]));
        schedL.setText(String.valueOf(sched[1]));
        schedN.setText(String.valueOf(sched[2]));
        schedH.setText(String.valueOf(sched[3]));
        schedVH.setText(String.valueOf(sched[4]));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schedVL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        schedL = new javax.swing.JTextField();
        schedN = new javax.swing.JTextField();
        schedH = new javax.swing.JTextField();
        schedVH = new javax.swing.JTextField();
        jok = new javax.swing.JButton();
        jreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        schedVL.setBackground(new java.awt.Color(204, 204, 204));
        schedVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedVL.setText("1.43");
        schedVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedVLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("NOM");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("VLOW");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("LOW");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("VHIGH");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("HIGH");

        schedL.setBackground(new java.awt.Color(204, 204, 204));
        schedL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedL.setText("1.14");
        schedL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedLActionPerformed(evt);
            }
        });

        schedN.setBackground(new java.awt.Color(204, 204, 204));
        schedN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedN.setText("1.00");
        schedN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedNActionPerformed(evt);
            }
        });

        schedH.setBackground(new java.awt.Color(204, 204, 204));
        schedH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedH.setText("1.00");
        schedH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedHActionPerformed(evt);
            }
        });

        schedVH.setBackground(new java.awt.Color(204, 204, 204));
        schedVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        schedVH.setText("1.00");
        schedVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedVHActionPerformed(evt);
            }
        });

        jok.setBackground(new java.awt.Color(102, 255, 102));
        jok.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jok.setText("OK");
        jok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jokActionPerformed(evt);
            }
        });

        jreset.setBackground(new java.awt.Color(102, 255, 102));
        jreset.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jreset.setText("RESET");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(schedVL, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(schedL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(schedN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(schedH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(schedVH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jreset)
                .addGap(59, 59, 59)
                .addComponent(jok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schedVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schedL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schedN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schedH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schedVH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jok)
                    .addComponent(jreset))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schedVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schedVLActionPerformed

    private void schedLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schedLActionPerformed

    private void schedNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schedNActionPerformed

    private void schedHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schedHActionPerformed

    private void schedVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedVHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schedVHActionPerformed

    private void jokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jokActionPerformed
        // TODO add your handling code here:
        boolean legal = true;
        
        legal &= validateDouble(schedVL.getText());
        legal &= validateDouble(schedL.getText());
        legal &= validateDouble(schedN.getText());
        legal &= validateDouble(schedH.getText());
        legal &= validateDouble(schedVH.getText());
        
        if(legal){
        changeScheduleValues();
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid Input", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jokActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        // TODO add your handling code here:
        resetScheduleValues();
    }//GEN-LAST:event_jresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SCHEDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SCHEDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SCHEDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SCHEDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SCHEDefault().setVisible(true);
            }
        });
    }
    
     
        private boolean validateDouble(String s){
            String ss = s.replace(" ","");
            if(ss.length()==0) return false;
            else return Pattern.matches("^(0\\.\\d*[1-9]\\d*)|([1-9]\\d*(\\.\\d+)?)$",
				ss);
        }
    
    	private void changeScheduleValues() {
        sched[0] = Double.valueOf(schedVL.getText());
        sched[1] = Double.valueOf(schedL.getText());
        sched[2] = Double.valueOf(schedN.getText());
        sched[3] = Double.valueOf(schedH.getText());
        sched[4] = Double.valueOf(schedVH.getText());
	}
        

	private void resetScheduleValues() {
	for(int i = 0; i < 5; ++i) sched[i] = defSched[i];

        schedVL.setText(String.valueOf(sched[0]));
        schedL.setText(String.valueOf(sched[1]));
        schedN.setText(String.valueOf(sched[2]));
        schedH.setText(String.valueOf(sched[3]));
        schedVH.setText(String.valueOf(sched[4]));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jok;
    private javax.swing.JButton jreset;
    private javax.swing.JTextField schedH;
    private javax.swing.JTextField schedL;
    private javax.swing.JTextField schedN;
    private javax.swing.JTextField schedVH;
    private javax.swing.JTextField schedVL;
    // End of variables declaration//GEN-END:variables
}
