
package cocomoJava;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 * This class implements Scale-factors that account for the relative economies
 * of scale encountered for software projects of different sizes
 *
 * @author preethijprabhu
 * @version 1.0.0.0
 */
public class SFactor extends javax.swing.JDialog {

    final int SFACTOR_COUNT = 5;
    private static DecimalFormat df2 = new DecimalFormat(".##");
    private double[] precWeight, flexWeight, reslWeight, teamWeight, pmatWeight;
    private String[] sfRating;
    private double netScaleFactor;
    private CocomoDashboard cocoDash;

    /**
     * Creates new form SFactor
     */
    public SFactor(java.awt.Frame parent, boolean modal, String[] sfRating) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.cocoDash  = (CocomoDashboard) parent;
        this.sfRating  = sfRating;
        netScaleFactor = 0.0;
        precWeight = new double[SFACTOR_COUNT];
        flexWeight = new double[SFACTOR_COUNT];
        reslWeight = new double[SFACTOR_COUNT];
        teamWeight = new double[SFACTOR_COUNT];
        pmatWeight = new double[SFACTOR_COUNT];
        setDefaultLevels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmatLabel = new java.awt.Label();
        teamLabel = new java.awt.Label();
        precLabel = new java.awt.Label();
        precCombo = new javax.swing.JComboBox<>();
        reslLabel = new java.awt.Label();
        flexLabel = new java.awt.Label();
        teamCombo = new javax.swing.JComboBox<>();
        reslCombo = new javax.swing.JComboBox<>();
        flexCombo = new javax.swing.JComboBox<>();
        pmatCombo = new javax.swing.JComboBox<>();
        scaleOkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCALE FACTOR");

        pmatLabel.setBackground(new java.awt.Color(255, 255, 255));
        pmatLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pmatLabel.setText("Process Maturity (PMAT) :");

        teamLabel.setBackground(new java.awt.Color(255, 255, 255));
        teamLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        teamLabel.setText("Team Cohesion (TEAM) :");

        precLabel.setBackground(new java.awt.Color(255, 255, 255));
        precLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        precLabel.setText("Precedentedness (PREC) :");

        precCombo.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        precCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VLOW", "LOW", "NOM", "HIGH", "VHIGH" }));

        reslLabel.setBackground(new java.awt.Color(255, 255, 255));
        reslLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reslLabel.setText("Archi / Risk Resolution (RESL) :");

        flexLabel.setBackground(new java.awt.Color(255, 255, 255));
        flexLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        flexLabel.setText("Development Flexibility (FLEX) :");

        teamCombo.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        teamCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VLOW", "LOW", "NOM", "HIGH", "VHIGH" }));

        reslCombo.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        reslCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VLOW", "LOW", "NOM", "HIGH", "VHIGH" }));

        flexCombo.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        flexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VLOW", "LOW", "NOM", "HIGH", "VHIGH" }));

        pmatCombo.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        pmatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VLOW", "LOW", "NOM", "HIGH", "VHIGH" }));

        scaleOkBtn.setBackground(new java.awt.Color(102, 255, 102));
        scaleOkBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        scaleOkBtn.setText("OK");
        scaleOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleOkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(flexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flexCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scaleOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(precLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pmatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reslLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pmatCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teamCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reslCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flexCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reslLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reslCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pmatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scaleOkBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDefaultLevels() {
        SFDefault defaultWeight = new SFDefault();
        for (int i = 0; i < SFACTOR_COUNT; i++) {
            precWeight[i] = defaultWeight.prec[i];
            flexWeight[i] = defaultWeight.flex[i];
            reslWeight[i] = defaultWeight.resl[i];
            teamWeight[i] = defaultWeight.team[i];
            pmatWeight[i] = defaultWeight.pmat[i];
        }

        precCombo.setSelectedItem(sfRating[0]);
        flexCombo.setSelectedItem(sfRating[1]);
        reslCombo.setSelectedItem(sfRating[2]);
        teamCombo.setSelectedItem(sfRating[3]);
        pmatCombo.setSelectedItem(sfRating[4]);

    }

    private void scaleOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleOkBtnActionPerformed

        netScaleFactor = (precWeight[precCombo.getSelectedIndex()]
                + flexWeight[flexCombo.getSelectedIndex()]
                + reslWeight[reslCombo.getSelectedIndex()]
                + teamWeight[teamCombo.getSelectedIndex()]
                + pmatWeight[pmatCombo.getSelectedIndex()]);

        sfRating[0] = precCombo.getSelectedItem().toString();
        sfRating[1] = flexCombo.getSelectedItem().toString();
        sfRating[2] = reslCombo.getSelectedItem().toString();
        sfRating[3] = teamCombo.getSelectedItem().toString();
        sfRating[4] = pmatCombo.getSelectedItem().toString();

        this.cocoDash.setScaleFactor(String.valueOf(df2.format(netScaleFactor)), sfRating);
        this.setVisible(false);
    }//GEN-LAST:event_scaleOkBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SFactor dialog = new SFactor(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> flexCombo;
    private java.awt.Label flexLabel;
    private javax.swing.JComboBox<String> pmatCombo;
    private java.awt.Label pmatLabel;
    private javax.swing.JComboBox<String> precCombo;
    private java.awt.Label precLabel;
    private javax.swing.JComboBox<String> reslCombo;
    private java.awt.Label reslLabel;
    private javax.swing.JButton scaleOkBtn;
    private javax.swing.JComboBox<String> teamCombo;
    private java.awt.Label teamLabel;
    // End of variables declaration//GEN-END:variables
}
