
package cocomoJava;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author preethijprabhu
 * @version 1.0.0.0
 */

public class SFDefault extends javax.swing.JFrame {

    public static double[] prec = {6.20, 4.96, 3.72, 2.48, 1.24};
	public static double[] flex = {5.07, 4.05, 3.04, 2.03, 1.01};
	public static double[] resl = {7.07, 5.65, 4.24, 2.83, 1.41};
	public static double[] team = {5.48, 4.38, 3.29, 2.19, 1.10};
	public static double[] pmat = {7.80, 6.24, 4.68, 3.12, 1.56};

    /**
     * Creates new form SFDefault
     */
    public SFDefault() {
       initComponents();
       this.setTitle("ScaleFactor Default Values");
       this.getContentPane().setBackground(Color.white);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        precVL = new javax.swing.JTextField();
        precL = new javax.swing.JTextField();
        precN = new javax.swing.JTextField();
        precH = new javax.swing.JTextField();
        precVH = new javax.swing.JTextField();
        flexL = new javax.swing.JTextField();
        flexN = new javax.swing.JTextField();
        flexH = new javax.swing.JTextField();
        flexVH = new javax.swing.JTextField();
        flexVL = new javax.swing.JTextField();
        reslL = new javax.swing.JTextField();
        reslN = new javax.swing.JTextField();
        reslH = new javax.swing.JTextField();
        reslVH = new javax.swing.JTextField();
        reslVL = new javax.swing.JTextField();
        teamL = new javax.swing.JTextField();
        teamN = new javax.swing.JTextField();
        teamH = new javax.swing.JTextField();
        teamVH = new javax.swing.JTextField();
        teamVL = new javax.swing.JTextField();
        pmatL = new javax.swing.JTextField();
        pmatN = new javax.swing.JTextField();
        pmatH = new javax.swing.JTextField();
        pmatVH = new javax.swing.JTextField();
        pmatVL = new javax.swing.JTextField();
        jOk = new javax.swing.JButton();
		jReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCALE FACTOR DEFAULT");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("PREC");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("FLEX");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("RESL");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("TEAM");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("PMAT");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("LOW");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("NOM");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("VHIGH");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("HIGH");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("VLOW");

        precVL.setEditable(true);
        precVL.setBackground(new java.awt.Color(204, 204, 204));
        precVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        precVL.setText(String.valueOf(prec[0]));

        precL.setEditable(true);
        precL.setBackground(new java.awt.Color(204, 204, 204));
        precL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        precL.setText(String.valueOf(prec[1]));

        precN.setEditable(true);
        precN.setBackground(new java.awt.Color(204, 204, 204));
        precN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        precN.setText(String.valueOf(prec[2]));

        precH.setEditable(true);
        precH.setBackground(new java.awt.Color(204, 204, 204));
        precH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        precH.setText(String.valueOf(prec[3]));

        precVH.setEditable(true);
        precVH.setBackground(new java.awt.Color(204, 204, 204));
        precVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        precVH.setText(String.valueOf(prec[4]));

		flexVL.setEditable(true);
        flexVL.setBackground(new java.awt.Color(204, 204, 204));
        flexVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        flexVL.setText(String.valueOf(flex[0]));

        flexL.setEditable(true);
        flexL.setBackground(new java.awt.Color(204, 204, 204));
        flexL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        flexL.setText(String.valueOf(flex[1]));

        flexN.setEditable(true);
        flexN.setBackground(new java.awt.Color(204, 204, 204));
        flexN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        flexN.setText(String.valueOf(flex[2]));

        flexH.setEditable(true);
        flexH.setBackground(new java.awt.Color(204, 204, 204));
        flexH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        flexH.setText(String.valueOf(flex[3]));

        flexVH.setEditable(true);
        flexVH.setBackground(new java.awt.Color(204, 204, 204));
        flexVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        flexVH.setText(String.valueOf(flex[4]));

		reslVL.setEditable(true);
        reslVL.setBackground(new java.awt.Color(204, 204, 204));
        reslVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reslVL.setText(String.valueOf(resl[0]));

        reslL.setEditable(true);
        reslL.setBackground(new java.awt.Color(204, 204, 204));
        reslL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reslL.setText(String.valueOf(resl[1]));

        reslN.setEditable(true);
        reslN.setBackground(new java.awt.Color(204, 204, 204));
        reslN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reslN.setText(String.valueOf(resl[2]));

        reslH.setEditable(true);
        reslH.setBackground(new java.awt.Color(204, 204, 204));
        reslH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reslH.setText(String.valueOf(resl[3]));

        reslVH.setEditable(true);
        reslVH.setBackground(new java.awt.Color(204, 204, 204));
        reslVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reslVH.setText(String.valueOf(resl[4]));

		teamVL.setEditable(true);
        teamVL.setBackground(new java.awt.Color(204, 204, 204));
        teamVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        teamVL.setText(String.valueOf(team[0]));

        teamL.setEditable(true);
        teamL.setBackground(new java.awt.Color(204, 204, 204));
        teamL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        teamL.setText(String.valueOf(team[1]));

        teamN.setEditable(true);
        teamN.setBackground(new java.awt.Color(204, 204, 204));
        teamN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        teamN.setText(String.valueOf(team[2]));

        teamH.setEditable(true);
        teamH.setBackground(new java.awt.Color(204, 204, 204));
        teamH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        teamH.setText(String.valueOf(team[3]));

        teamVH.setEditable(true);
        teamVH.setBackground(new java.awt.Color(204, 204, 204));
        teamVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        teamVH.setText(String.valueOf(team[4]));

		pmatVL.setEditable(true);
        pmatVL.setBackground(new java.awt.Color(204, 204, 204));
        pmatVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pmatVL.setText(String.valueOf(pmat[0]));

        pmatL.setEditable(true);
        pmatL.setBackground(new java.awt.Color(204, 204, 204));
        pmatL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pmatL.setText(String.valueOf(pmat[1]));

        pmatN.setEditable(true);
        pmatN.setBackground(new java.awt.Color(204, 204, 204));
        pmatN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pmatN.setText(String.valueOf(pmat[2]));

        pmatH.setEditable(true);
        pmatH.setBackground(new java.awt.Color(204, 204, 204));
        pmatH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pmatH.setText(String.valueOf(pmat[3]));

        pmatVH.setEditable(true);
        pmatVH.setBackground(new java.awt.Color(204, 204, 204));
        pmatVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pmatVH.setText(String.valueOf(pmat[4]));

        jOk.setBackground(new java.awt.Color(102, 255, 102));
        jOk.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jOk.setText("OK");
        jOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
				changeScaleFactorValues();
                jOkActionPerformed(evt);
            }
        });

		jReset.setBackground(new java.awt.Color(102, 255, 102));
        jReset.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetScaleFactorValues();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(precVL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precVH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flexVL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flexL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flexN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flexH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flexVH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reslVL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reslL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reslN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reslH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reslVH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teamVL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamVH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pmatVL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pmatL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pmatN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pmatH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pmatVH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
										.addGap(48, 48, 48)
                                        .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
									.addGroup(layout.createSequentialGroup()
										.addGap(48, 48, 48)
                                        .addComponent(jOk, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel10)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(precVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(flexVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flexL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flexN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flexH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flexVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reslVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reslL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reslN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reslH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reslVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(teamVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pmatVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmatL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmatN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmatH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmatVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jReset)
				.addComponent(jOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkActionPerformed
        try{
            prec[0] = Double.valueOf(precVL.getText());
            prec[1] = Double.valueOf(precL.getText());
            prec[2] = Double.valueOf(precN.getText());
            prec[3] = Double.valueOf(precH.getText());
            prec[4] = Double.valueOf(precVH.getText());

            flex[0] = Double.valueOf(flexVL.getText());
            flex[1] = Double.valueOf(flexL.getText());
            flex[2] = Double.valueOf(flexN.getText());
            flex[3] = Double.valueOf(flexH.getText());
            flex[4] = Double.valueOf(flexVH.getText());

            resl[0] = Double.valueOf(reslVL.getText());
            resl[1] = Double.valueOf(reslL.getText());
            resl[2] = Double.valueOf(reslN.getText());
            resl[3] = Double.valueOf(reslH.getText());
            resl[4] = Double.valueOf(reslVH.getText());

            team[0] = Double.valueOf(teamVL.getText());
            team[1] = Double.valueOf(teamL.getText());
            team[2] = Double.valueOf(teamN.getText());
            team[3] = Double.valueOf(teamH.getText());
            team[4] = Double.valueOf(teamVH.getText());

            pmat[0] = Double.valueOf(pmatVL.getText());
            pmat[1] = Double.valueOf(pmatL.getText());
            pmat[2] = Double.valueOf(pmatN.getText());
            pmat[3] = Double.valueOf(pmatH.getText());
            pmat[4] = Double.valueOf(pmatVH.getText());
            this.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Illegal inputs. Please re-enter");
        }
    }//GEN-LAST:event_jOkActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SFDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SFDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SFDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SFDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SFDefault().setVisible(true);
            }
        });
    }

	private void changeScaleFactorValues() {
            /*
            prec[0] = Double.valueOf(precVL.getText());
            prec[1] = Double.valueOf(precL.getText());
            prec[2] = Double.valueOf(precN.getText());
            prec[3] = Double.valueOf(precH.getText());
            prec[4] = Double.valueOf(precVH.getText());

            flex[0] = Double.valueOf(flexVL.getText());
            flex[1] = Double.valueOf(flexL.getText());
            flex[2] = Double.valueOf(flexN.getText());
            flex[3] = Double.valueOf(flexH.getText());
            flex[4] = Double.valueOf(flexVH.getText());

            resl[0] = Double.valueOf(reslVL.getText());
            resl[1] = Double.valueOf(reslL.getText());
            resl[2] = Double.valueOf(reslN.getText());
            resl[3] = Double.valueOf(reslH.getText());
            resl[4] = Double.valueOf(reslVH.getText());

            team[0] = Double.valueOf(teamVL.getText());
            team[1] = Double.valueOf(teamL.getText());
            team[2] = Double.valueOf(teamN.getText());
            team[3] = Double.valueOf(teamH.getText());
            team[4] = Double.valueOf(teamVH.getText());

            pmat[0] = Double.valueOf(pmatVL.getText());
            pmat[1] = Double.valueOf(pmatL.getText());
            pmat[2] = Double.valueOf(pmatN.getText());
            pmat[3] = Double.valueOf(pmatH.getText());
            pmat[4] = Double.valueOf(pmatVH.getText());
*/
	}

	private void resetScaleFactorValues() {
		for(int i = 0; i < 5; ++i) prec[i] = defPrec[i];
		for(int i = 0; i < 5; ++i) flex[i] = defFlex[i];
		for(int i = 0; i < 5; ++i) resl[i] = defResl[i];
		for(int i = 0; i < 5; ++i) team[i] = defTeam[i];
		for(int i = 0; i < 5; ++i) pmat[i] = defPmat[i];

        precVL.setText(String.valueOf(prec[0]));
        precL.setText(String.valueOf(prec[1]));
        precN.setText(String.valueOf(prec[2]));
        precH.setText(String.valueOf(prec[3]));
        precVH.setText(String.valueOf(prec[4]));

        flexVL.setText(String.valueOf(flex[0]));
        flexL.setText(String.valueOf(flex[1]));
        flexN.setText(String.valueOf(flex[2]));
        flexH.setText(String.valueOf(flex[3]));
        flexVH.setText(String.valueOf(flex[4]));

        reslVL.setText(String.valueOf(resl[0]));
        reslL.setText(String.valueOf(resl[1]));
        reslN.setText(String.valueOf(resl[2]));
        reslH.setText(String.valueOf(resl[3]));
        reslVH.setText(String.valueOf(resl[4]));

        teamVL.setText(String.valueOf(team[0]));
        teamL.setText(String.valueOf(team[1]));
        teamN.setText(String.valueOf(team[2]));
        teamH.setText(String.valueOf(team[3]));
        teamVH.setText(String.valueOf(team[4]));

        pmatVL.setText(String.valueOf(pmat[0]));
        pmatL.setText(String.valueOf(pmat[1]));
        pmatN.setText(String.valueOf(pmat[2]));
        pmatH.setText(String.valueOf(pmat[3]));
        pmatVH.setText(String.valueOf(pmat[4]));
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField flexH;
    private javax.swing.JTextField flexL;
    private javax.swing.JTextField flexN;
    private javax.swing.JTextField flexVH;
    private javax.swing.JTextField flexVL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jOk;
	private javax.swing.JButton jReset;
    private javax.swing.JTextField pmatH;
    private javax.swing.JTextField pmatL;
    private javax.swing.JTextField pmatN;
    private javax.swing.JTextField pmatVH;
    private javax.swing.JTextField pmatVL;
    private javax.swing.JTextField precH;
    private javax.swing.JTextField precL;
    private javax.swing.JTextField precN;
    private javax.swing.JTextField precVH;
    private javax.swing.JTextField precVL;
    private javax.swing.JTextField reslH;
    private javax.swing.JTextField reslL;
    private javax.swing.JTextField reslN;
    private javax.swing.JTextField reslVH;
    private javax.swing.JTextField reslVL;
    private javax.swing.JTextField teamH;
    private javax.swing.JTextField teamL;
    private javax.swing.JTextField teamN;
    private javax.swing.JTextField teamVH;
    private javax.swing.JTextField teamVL;

	private final double[] defPrec = {6.20, 4.96, 3.72, 2.48, 1.24};
	private final double[] defFlex = {5.07, 4.05, 3.04, 2.03, 1.01};
	private final double[] defResl = {7.07, 5.65, 4.24, 2.83, 1.41};
	private final double[] defTeam = {5.48, 4.38, 3.29, 2.19, 1.10};
	private final double[] defPmat = {7.80, 6.24, 4.68, 3.12, 1.56};
    // End of variables declaration//GEN-END:variables
}
